### ISSUE TITLE
Don't require execute bit if --artifact and --invoker provided

### ISSUE THREAD

**Issue by trisberg** [projectriff/command-function-buildpack#1]
Currently there is no way to create a command function on Windows since there is no way to set the execute bit. If the user provides bot `--artifact` and `--invoker` I think the buildpack should accept the command and set the execute bit on the command file. This would allow the Windows user to run local-path builds from the PowerShell.

**Comment by scothis** [comment]
This feels like a more generic problem that buildpacks need to solve. Do they have a recommendation?

I'd to avoid automatically flipping that bit since if the target artifacts invokes another file without the bit that should have it, it will fail in an even more mysterious way.

**Comment by scothis** [comment]
Replaced by #10
